# The Docker image that will be used to build your app
image: node:lts
pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - rm .public/vp.js
  - mv .public/vp.production.js .public/vp.js
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - main
